repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        name: Black styler
        language_version: python3.10
        stages: [commit]
  - repo: https://github.com/lorenzwalthert/pre-commit-hooks
    rev: v0.3.1
    hooks: 
    -  id: style-files
       args: [--indent_by=4]
    -  id: roxygenize
    -  id: use-tidy-description
